#!/usr/bin/env sh

source "$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/scripts/configs/general.sh"

########## CONFIG START ##########

# WIDTH
# THIS VALUE SHOULD MATCH THE NOTCH SIZE, APPEARENCE WISE
EXPAND_WIDTH=${P_DYNAMIC_ISLAND_APPSWITCH_EXPAND_WIDTH:=152}

# MAX SIZE WHEN EXPANDED
MAX_EXPAND_WIDTH=${P_DYNAMIC_ISLAND_APPSWITCH_MAX_EXPAND_WIDTH:=285}

# HEIGHT
EXPAND_HEIGHT=${P_DYNAMIC_ISLAND_APPSWITCH_EXPAND_HEIGHT:=65}

# CORNER RADIUS
CORNER_RAD=${P_DYNAMIC_ISLAND_APPSWITCH_CORNER_RAD:=15}

# ICON SIZE
ICON_SIZE=${P_DYNAMIC_ISLAND_APPSWITCH_ICON_SIZE:=0.4}

########## NO NEED TO CONFIGURE BELOW ###########
SQUISH_WIDTH=$(($EXPAND_WIDTH-$SQUISH_AMOUNT))
MAX_EXPAND_SQUISH_WIDTH=$(($MAX_EXPAND_WIDTH+$SQUISH_AMOUNT))
MAX_EXPAND_HEIGHT=$(($EXPAND_HEIGHT+$SQUISH_AMOUNT))
