#!/usr/bin/env/sh

# DYNAMIC ISLAND MODULES:
MUSIC_ENABLED=1
APPSWITCH_ENABLED=1
NOTIFICATION_ENABLED=1
VOLUME_ENABLED=1

# FONT
FONT="SF Pro"

# COLORS
WHITE=0xffffffff
PITCH_BLACK=0xff000000
TRANSPARENT=0x00000000
ICON_HIDDEN=$PITCH_BLACK
DEFAULT_LABEL=$WHITE
TRANSPARENT_LABEL=$TRANSPARENT

# NOTCH SIZE
MAX_HEIGHT=90
DEFAULT_HEIGHT=65
DEFAULT_WIDTH=205
DEFAULT_CORNER_RADIUS=16

# ANIMATION SETTINGS
SQUISH_AMOUNT=7
