#!/usr/bin/env sh
VOLUME_MAX=${P_DYNAMIC_ISLAND_ICON_VOLUME_MAX:=􀊩}
VOLUME_MED=${P_DYNAMIC_ISLAND_ICON_VOLUME_MED:=􀊧}
VOLUME_LOW=${P_DYNAMIC_ISLAND_ICON_VOLUME_LOW:=􀊥}
VOLUME_MUTED=${P_DYNAMIC_ISLAND_ICON_VOLUME_MUTED:=􀊡}
