#!/usr/bin/env sh

source "$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/scripts/configs/general.sh"

########## CONFIG START ##########
# WIDTH
# THIS VALUE SHOULD MATCH THE NOTCH SIZE, APPEARENCE WISE
EXPAND_WIDTH=${P_DYNAMIC_ISLAND_NOTIFICATION_EXPAND_WIDTH:=150}

# MAX SIZE WHEN EXPANDED
MAX_EXPAND_WIDTH=${P_DYNAMIC_ISLAND_NOTIFICATION_MAX_EXPAND_WIDTH:=390}

# HEIGHT
EXPAND_HEIGHT=${P_DYNAMIC_ISLAND_NOTIFICATION_EXPAND_HEIGHT:=170}

# CORNER RADIUS
CORNER_RAD=${P_DYNAMIC_ISLAND_NOTIFICATION_CORNER_RAD:=28}

# MAX ALLOWED BODY FOR NOTIFICATION MESSAGE
MAX_ALLOWED_BODY=${P_DYNAMIC_ISLAND_NOTIFICATION_MAX_ALLOWED_BODY:=280}

########## NO NEED TO CONFIGURE BELOW ###########
SQUISH_WIDTH=$(($EXPAND_WIDTH-$SQUISH_AMOUNT))
MAX_EXPAND_SQUISH_WIDTH=$(($MAX_EXPAND_WIDTH+$SQUISH_AMOUNT))
MAX_EXPAND_HEIGHT=$(($EXPAND_HEIGHT+$SQUISH_AMOUNT))
