#!/usr/bin/env sh

source "$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/scripts/configs/general.sh"

########## CONFIG START ##########
# WIDTH
# THIS VALUE SHOULD MATCH THE NOTCH SIZE, APPEARENCE WISE
EXPAND_WIDTH=93

# MAX SIZE WHEN EXPANDED
MAX_EXPAND_WIDTH=260

# HEIGHT
EXPAND_HEIGHT=140

# CORNER RADIUS
CORNER_RAD=42

# MAX ALLOWED BODY FOR NOTIFICATION MESSAGE
MAX_ALLOWED_BODY=250

########## NO NEED TO CONFIGURE BELOW ###########
SQUISH_WIDTH=$(($EXPAND_WIDTH-$SQUISH_AMOUNT))
MAX_EXPAND_SQUISH_WIDTH=$(($MAX_EXPAND_WIDTH+$SQUISH_AMOUNT))
MAX_EXPAND_HEIGHT=$(($EXPAND_HEIGHT+$SQUISH_AMOUNT))
