#!/usr/bin/env sh

source "$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/scripts/configs/general.sh"

########## CONFIG START ##########

# WIDTH
# THIS VALUE SHOULD MATCH THE NOTCH SIZE, APPEARENCE WISE
EXPAND_WIDTH=192

# MAX SIZE WHEN EXPANDED
MAX_EXPAND_WIDTH=250

# HEIGHT
DEFAULT_HEIGHT=13
EXPAND_HEIGHT=16

# CORNER RADIUS
CORNER_RAD=12

# COLORS
NORMAL_ICON_COLOR=0xffffffff

########## NO NEED TO CONFIGURE BELOW ###########
SQUISH_WIDTH=$(($EXPAND_WIDTH-$SQUISH_AMOUNT))
MAX_EXPAND_SQUISH_WIDTH=$(($MAX_EXPAND_WIDTH+$SQUISH_AMOUNT))
MAX_EXPAND_HEIGHT=$(($EXPAND_HEIGHT+$SQUISH_AMOUNT))
